events/urls.py
from django.urls import path
from . import views

app_name = 'events'
urlpatterns = [
    path('', views.events, name='events'),
    path('<str:event_id>/', views.full_event, name='full_event'),
    path('<str:event_id>/propagate', views.propagate, name='propagate'),
    path('<str:event_id>/admit', views.admit, name='admit'),
    path('<str:event_id>/admit/<str:username>', views.admit_user, name='admit_user'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('end_quarter/', views.end_quarter, name='end_quarter'),
    path('profile/update/', views.update, name='update'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('', include('django.contrib.auth.urls')),
    path('badges/', include('badges.urls')),
    path('events/', include('events.urls')),
    path('admin/', admin.site.urls),
    path('leaderboard/', include('leaderboard.urls')),
    path('prizes/', include('prizes.urls')),
    path('user/', include('user.urls')),
    path('', include('qr_code.urls', namespace='qr_code')),
    path('', include('pwa.urls')),  # You MUST use an empty string as the URL prefix
]

events/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
User = get_user_model()
from django import forms
import uuid

class Tag(models.Model):
    tag = models.CharField(max_length=100)
    colour = models.CharField(max_length=100)
    def __str__(self):
        return self.tag

class Event(models.Model):
    event_title = models.CharField(max_length=200)
    organizer = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to={'is_staff': True}, related_name='organizer')
    pub_date = models.DateTimeField('date added', default=timezone.now())
    start_date = models.DateField()
    start_time = models.TimeField()
    end_date = models.DateField()
    end_time = models.TimeField()
    points = models.IntegerField(default=0)
    description = models.TextField(blank=True)
    location = models.CharField(max_length=200, default="School")
    image = models.ImageField(upload_to='static/img/event_images/', null=True, blank=True)
    interested = models.ManyToManyField(User, blank=True, related_name='interested')
    participants = models.ManyToManyField(User, blank=True, related_name='participants')
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    tags = models.ManyToManyField(Tag, blank=True)
    visibility = models.BooleanField(default=False)
    points_propagated = models.BooleanField(default=False)
    
    def __str__(self):
        return self.event_title
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    #def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get("start_date")
        end_date = cleaned_data.get("end_date")
        if end_date < start_date:
            raise forms.ValidationError("End date should be greater than start date.")
        if start_date == end_date:
            start_time = cleaned_data.get("start_time")
            end_time = cleaned_data.get("end_time")
            if end_time < start_time:
                raise forms.ValidationError("End time should be greater than start time.")
        return {'start_date': start_date, 'end_date': end_date, 'start_time': start_time, 'end_time': end_time}
    

"""
# not checked / temp rn
class Participation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    participation_date = models.DateField(auto_now_add=True)
    
# not checked temp rn
class Point(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    points = models.IntegerField()
    point_date = models.DateField(auto_now_add=True)
"""

events/views.py
from django.shortcuts import render
from .models import Event
from django.http import HttpResponseRedirect, Http404
from django.contrib import messages
from django.utils import timezone
from datetime import date
from mysite.config import today_date, today_time
from django.contrib.auth import get_user_model
User = get_user_model()


# display events
def events(request):
    events_list = Event.objects.order_by('-start_date', '-start_time')
    
    curr_date = today_date if today_date else date.today()
    curr_time = today_time if today_time else timezone.now().time()

    for event in events_list:
        # mark as upcoming, ongoing, ended
        event_status = 'upcoming'
        colour = '#bcf1b8'
        if event.start_date < curr_date or (event.start_date == curr_date and event.start_time < curr_time):
            event_status = 'ongoing'
            colour = '#ffeaca'
        if event.end_date < curr_date or (event.end_date == curr_date and event.end_time < curr_time):
            event_status = 'ended'
            colour = '#ffcaca'
        event.status = event_status
        event.colour = colour
    content = {'events_list': events_list}
    return render(request, 'events/events.html', content)

# display event details
def full_event(request, event_id):
    try:
        event = Event.objects.get(pk=event_id)
    except Event.DoesNotExist:
        raise Http404("Event does not exist")
    if request.method == "POST":
        if request.user in event.interested.all():
            event.interested.remove(request.user)
            request.user.events_interested.remove(event)
            messages.info(request, "You are no longer interested in this event")
        else:
            event.interested.add(request.user)
            request.user.events_interested.add(event)
            messages.success(request, "You are now interested in this event")
        return HttpResponseRedirect(request.path_info)
    manager, organizer = False, False
    if request.user == event.organizer or request.user.is_staff or request.user.is_superuser:
        manager = True
    if request.user == event.organizer:
        organizer = True
    
    curr_date = today_date if today_date else date.today()
    curr_time = today_time if today_time else timezone.now().time()

    print(curr_date, curr_time)

    event_started = False
    if event.start_date < curr_date or (event.start_date == curr_date and event.start_time < curr_time):
        event_started = True
    event_ended = False
    if event.end_date < curr_date or (event.end_date == curr_date and event.end_time < curr_time):
        event_ended = True
    
    return render(request, 'events/full_event.html', {'event': event, 'manager': manager, 'organizer': organizer, 'event_started': event_started, 'event_ended': event_ended})

# admit users to event
def admit(request, event_id):
    try:
        event = Event.objects.get(pk=event_id)
    except Event.DoesNotExist:
        raise Http404("Event does not exist")
    if not (request.user == event.organizer or request.user.is_staff or request.user.is_superuser):
        raise Http404("You are not the organizer of this event")
    
    users = event.interested.all().order_by('-last_name')
    if request.method == "POST":
        checked_users = request.POST.getlist('admit')
        for user in users:
            if user.username in checked_users and user not in event.participants.all():
                event.participants.add(user)
                user.events_participated.add(event)
            elif user.username not in checked_users and user in event.participants.all():
                event.participants.remove(user)
                user.events_participated.remove(event)
        messages.success(request, "Attendance has been updated")
        return HttpResponseRedirect(request.path_info)
    return render(request, 'events/admit.html', {'event': event, 'users': users})

# admit a single user to event
def admit_user(request, event_id, username):
    try:
        event = Event.objects.get(pk=event_id)
    except Event.DoesNotExist:
        raise Http404("Event does not exist")
    if not (request.user == event.organizer or request.user.is_staff or request.user.is_superuser):
        raise Http404("You are not the organizer of this event")
    try:
        user = User.objects.filter(username=username).first()
    except User.DoesNotExist:
        raise Http404(f"{user.username} does not exist")
    if user in event.interested.all() and user not in event.participants.all():
        event.participants.add(user)
        user.events_participated.add(event)
        messages.success(request, f"{user.username} has been admitted")
    elif user not in event.interested.all():
        messages.info(request, f"{user.username} is not interested in this event")
    else:
        messages.info(request, f"{user.username} is already admitted")
    event.save()
    user.save()
    return HttpResponseRedirect('../')

# propagate points
def propagate(request, event_id):
    try:
        event = Event.objects.get(pk=event_id)
    except Event.DoesNotExist:
        raise Http404("Event does not exist")
    if not (request.user == event.organizer or request.user.is_staff or request.user.is_superuser):
        raise Http404("You are not the organizer of this event")
    if event.points_propagated:
        raise Http404("Points have already been propagated")
    users = event.participants.all()
    print(users)
    for user in users:
        user.points_alltime += event.points
        user.points_quarterly += event.points
        user.coins += event.points
        user.save()
    event.points_propagated = True
    event.save()
    messages.success(request, "Points have been propagated")
    return HttpResponseRedirect('../')

templates/events/admit.html
{% extends 'base.html' %} 

{% block title %}Admit{% endblock %} 

{% block content %} 
    <h1>Admit</h1> 
    <form action="" method=POST> 
        {% csrf_token %} 
        <table>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Admit</th>
            </tr>
            {% for user in users %}
                <tr>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.last_name }}</td>
                    <td>
                        {% if user in event.participants.all %}
                            <input type="checkbox" name="admit" value="{{ user.username }}" checked>
                        {% else %}
                            <input type="checkbox" name="admit" value="{{ user.username }}">
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
        <input type="submit" value="Admit"> 
    </form> 
{% endblock %}

templates/events/events.html
{% extends "base.html" %}
{% block content %}


<script src="/static/jquery-3.4.1.js" type="text/javascript"></script>
<script src="/static/bootstrap.js" type="text/javascript"></script>

<div class="row" style="margin-top: 7%;  margin-bottom: 3%;">
    <h1 style="text-align: center; margin-bottom: 0%;">events</h1>
    <p style="text-align: center;">These events are only the tip of the iceberg.</p>
</div>
{% if events_list %}
<div class="row gx-5">
    {% for event in events_list %}
    <div class="col-md-4 col-sm-2 event-card card">

        <div class="card-body">
            <div class="row">
                <div class="col">
                    <h6 class="card-subtitle mb-2 text-muted badge" style="background-color: {{event.colour}}">{{event.status }}</h6>

                    <a href="{% url 'events:full_event' event.id %}" class="card-title stretched-link" style="text-decoration: none; color:#523911"><h5>{{ event.event_title }}</h5></a>
                    <h6 class="card-subtitle mb-2 text-muted">{{ event.organizer }}</h6>
                    <!--<p class="card-text">{{ event.description|truncatechars:50 }}</p>-->
                    <span class="bi bi-geo-alt"> {{ event.location }}</span>
                    <br>
                    <span class="bi bi-calendar-event"> {{ event.start_date }} @ {{ event.start_time }} - {{event.end_date }} @ {{ event.end_time }}</span>
                    <div class="card-footer">{% if user in event.interested.all %} <p class="card-text"></p>interested!</p> {% endif %}
                        {% if user in event.participants.all %} <p class="card-text"></p>participant!</p> {% endif %}
                    </div>
                </div>
                <div class="col points-blob text-center vertical-center-smol" style="max-width: 5rem;">
                    <div class="">
                    <p class="points-num align-middle" style=" margin-bottom: 0">{{ event.points }}</p>
                    <p class="">points</p>
                    </div>
                </div>
            </div>

        </div>
    </div>
    {% endfor %}

</div>
{% else %}
<p>No events found.</p>
{% endif %}


</form>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
    </script>


{% endblock content %}

templates/events/full_event.html
{% extends "base.html" %}
{% load qr_code %}
{% block content %}


<script src="/static/jquery-3.4.1.js" type="text/javascript"></script>
<script src="/static/bootstrap.js" type="text/javascript"></script>

<div class="container body-content" style="max-width:60rem">
    <div class="row" style="margin-top: 5%;  margin-bottom: 3%;">
        <h1 style="text-align: center;">{{ event.event_title }}</h1>
        <p class="smaller text-center">{{ event.pub_date }} | {{ event.organizer }}
            {% if organizer %}
            | <a href="{% url 'admin:events_event_change' event.id %}">edit</a>
            {% endif %}
        </p>

        <p><b>date and time: </b>{{ event.start_date }} @ {{ event.start_time }} - {{ event.end_date }} @ {{ event.end_time }}</p>
        <p><b>location: </b>{{ event.location }}</p>
        <p><b>points: </b>{{ event.points }}</p>
        <p>{{ event.description }}</p>
        <p><b></b></p>{% if user in event.participants.all %} <p>participant!</p> {% endif %} 
        <p><b>interest: </b>{% if user in event.interested.all %}yes

        <img src="{% qr_url_from_text request.get_host|add:'/event/'|add:'event.id'|add:'/admit/'|add:user.username size='S' %}" class="qr" alt="{{user.username}}" id="img">
        <div id="myModal" class="modal">
            <!-- Modal Content (The Image) -->
            <img class="modal-content" id="img01">
            <!-- Modal Caption (Image Text) -->
            <div id="caption" class="close">{{user.username}} (close)</div>
        </div>

        {% else %}no
        {% endif %}
        <p>{{event.interested.all.count}} people are interested!</p>
        <b>tags:</b>
        {% for tag in event.tags.all %}
        <span>- {{tag}}</span>
        {% endfor %}
        {% if not event_started %}
        <br><br>
        {% if not user.is_authenticated %}
        <p>Please log in to do interest.</p>
        {% else %}
        <form method="POST">
            {% csrf_token %}
            <button type="submit" class="btn-block btn btn-primary" style="background:rgba(126, 139, 77, 1);border-color: rgba(126, 139, 77, 1); border-radius:3rem; margin-top:1%" >
                {% if user in event.interested.all %}
                    Remove interest
                {% else %}
                    Add interest
                {% endif %}
            </button>
        </form>
        {% endif %}
        {% endif %}
        {% if manager %}
            {% if event_started and not event_ended %}
            <a href="/events/{{event.id}}/admit">
                <button type="submit" class="btn-block btn btn-primary"
                    style="background:rgba(126, 139, 77, 1);border-color: rgba(126, 139, 77, 1); border-radius:3rem; margin-top:1%">admit</button>
            </a>
            {% elif event_ended %}
                {% if not event.points_propagated %}
                <a href="/events/{{event.id}}/propagate">
                    <button type="submit" class="btn-block btn btn-primary"
                        style="background:rgba(126, 139, 77, 1);border-color: rgba(126, 139, 77, 1); border-radius:3rem; margin-top:1%">Propogate
                        Points</button>
                </a>
                {% else %}
                <p> </p>
                <p>Points have been propagated.</p>
                {% endif %}
            {% endif %}
        {% endif %}
    </div>
</div>

</form>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
    </script>

<script>
    // Get the modal
    var modal = document.getElementById("myModal");

    // Get the image and insert it inside the modal - use its "alt" text as a caption
    var img = document.getElementById("img");
    var modalImg = document.getElementById("img01");
    var captionText = document.getElementById("caption");
    img.onclick = function () {
        modal.style.display = "block";
        modalImg.src = this.src;
    }

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    // When the user clicks on <span> (x), close the modal
    span.onclick = function () {
        modal.style.display = "none";
    }
</script>
<style>
    /* Style the Image Used to Trigger the Modal */
    #myImg {
        border-radius: 5px;
        cursor: pointer;
        transition: 0.3s;
    }

    #myImg:hover {
        opacity: 0.7;
    }

    /* The Modal (background) */
    .modal {
        display: none;
        /* Hidden by default */
        position: fixed;
        /* Stay in place */
        z-index: 1;
        /* Sit on top */
        padding-top: 100px;
        /* Location of the box */
        left: 0;
        top: 0;
        width: 100%;
        /* Full width */
        height: 100%;
        /* Full height */
        overflow: auto;
        /* Enable scroll if needed */
        background-color: rgb(0, 0, 0);
        /* Fallback color */
        background-color: rgba(0, 0, 0, 0.9);
        /* Black w/ opacity */
    }

    /* Modal Content (Image) */
    .modal-content {
        margin: auto;
        display: block;
        width: 80%;
        max-width: 700px;
    }

    /* Caption of Modal Image (Image Text) - Same Width as the Image */
    #caption {
        margin: auto;
        display: block;
        width: 80%;
        max-width: 700px;
        text-align: center;
        color: #ccc;
        padding: 10px 0;
        height: 150px;
    }

    /* Add Animation - Zoom in the Modal */
    .modal-content,
    #caption {
        animation-name: zoom;
        animation-duration: 0.6s;
    }

    @keyframes zoom {
        from {
            transform: scale(0)
        }

        to {
            transform: scale(1)
        }
    }

    .close:hover,
    .close:focus {
        color: #bbb;
        text-decoration: none;
        cursor: pointer;
    }

    /* 100% Image Width on Smaller Screens */
    @media only screen and (max-width: 700px) {
        .modal-content {
            width: 100%;
        }
    }
</style>
{% endblock content %}